version: '3'
services:
  app:

    container_name : NodeFinal
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports : 
      - '4444:4444'
    links:
      - mongo

  mongo: 
     container_name : mongo
     image : mongo